### ISSUE TITLE
IncomingEntry::isFailedJob always returns false

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/telescope#1022]
- Telescope Version: 4.4.4
- Laravel Version: 8.30.0
- PHP Version: 8.0.02
- Database Driver & Version: mySQL 8.0.22

Duplicate of https://github.com/laravel/telescope/issues/881 with reproducible steps on the latest version.

### Description:
`IncomingEntry::isFailedJob` never returns true. Failed jobs are always recorded as an update and not as inserts, which is quite understandable as the job entry will be created when the job is dispatched, and the update entry is created when the job fails or completes processing. This means that an `IncomingEntry` (insert) can never actually be a failed job and a failed job would always be a `EntryUpdate`.

### Steps To Reproduce:

In a fresh Laravel installation:

1. Make sure queue driver is not sync. Set to `redis` or `database`.
2. Create a TestJob that throws an Exception in the `handle` method.
3. Add this to `TelescopeServiceProvider`:
```php
Telescope::filterBatch(function (Collection $entries) {
    return $entries->contains(function (IncomingEntry $entry) {
        return $entry->isFailedJob();
    });
});
```
4. Run the queue worker with Horizon or `queue:work`.
5. Check Telescope entries. You will not find any entry related to a failed job even though the job had indeed failed.

### Possible Solutions

I'm happy to submit a PR for this but I'm not quite sure what the solution would be. Here's a couple that I thought of:

1. Pass both the `entriesQueue` and the `updatesQueue` to the `filterBatchUsing` callback. This way, the logic for `isFailedJob` will work properly if implemented in `EntryUpdate`. This will be a breaking change if people use a method that's available on `IncomingEntry` but not on `EntryUpdate`. Perhaps `EntryUpdate` could extend `IncomingEntry`?
2. Remove the method `isFailedJob` and just add a `isJob` method. This is a breaking change and would need a major update.
3. Add another callback for filtering update entries in batches. Not a breaking change but I think it may actually confuse people who don't know the inner workings of Telescope.

I'd recommend implementing option 1. Would love to hear your thoughts and would be happy to submit a PR if you'd like once we decide on the solution. Thanks!

Ping @themsaid.

**Comment by driesvints** [comment]
Hey @paras-malhotra, I talked to @themsaid and we think the first option is probably the best one. If there's a chance to let EntryUpdate extend IncomingEntry then that could maybe be a solution.

**Comment by paras-malhotra** [comment]
Sure thanks @driesvints, I'll look into this towards the end of the week and send across a PR. 👍

**Comment by driesvints** [comment]
@paras-malhotra feel free to send in that PR when you can 👍

**Comment by antoinelame** [comment]
Hey @driesvints and @themsaid,

This issue is still present and makes impossible the monitoring of failed jobs in production. That's quite annoying and I'd love to help with this and submit a PR. 👍 

However, I didn't quite understand the suggested solution using the `filterBatchUsing` callback. Using it, how could we prevent one Job entry from being stored without preventing the whole batch?

**Comment by luanmm** [comment]
What is the purpose of the method `isFailedJob()` at all, then? Keeping the way it is, it should be entirely removed, at least, to not make developers believe that it works as expected.

**Comment by justinkekeocha** [comment]
I just encountered this issue and resolved it for now. The problem has already been explained in the description above, so I won't go into further detail. I updated the TelescopeServiceProvider's register method to the following:

`
 Telescope::filter(function (IncomingEntry $entry) {

            if ($this->app->environment('local')) {
                return true;
            }

            if (
                $entry->hasMonitoredTag() ||
                $entry->isFailedRequest() ||
                $entry->isSlowQuery() ||
                in_array($entry->type, [
                    EntryType::JOB,
                ])
            ) {
                return true;
            }

            return false;
        });`

With the above setup, Laravel will record all jobs. This is necessary because, as explained earlier, every job entry starts in a pending status and never failed. Whether the job is marked as failed or processed is determined in an update statement. Therefore, we need to insert the potentially failing job first so it can be updated to 'failed' if it fails.

Then create a command 

`
namespace App\Console\Commands;

use Illuminate\Console\Command;
use Laravel\Telescope\EntryType;
use Illuminate\Database\Eloquent\Builder;
use Laravel\Telescope\Storage\EntryModel;

class DeleteUnwantedTelescopeEntries extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:delete-unwanted-telescope-entries';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {

        EntryModel::where(function (Builder $query) {
            $query
                ->where('type', EntryType::JOB)
                //WE need to leave pending job, so it can be updated by telescope to failed.
                ->whereNotIn('content->status', ['pending', 'failed']);
        })->delete();
    }
}
`

The above command deletes telescope job entries where the status of the job is not pending or failed.

You can then go on to queue this command so it can be leave only pending and failed jobs

**Comment by luanmm** [comment]
So this should be handled by Telescope, not in custom code.

I really don't know why Laravel community keeps putting Laravel status as a framework below where it should be. Sometimes feels like everyone is thinking about it as a replacement for Wordpress, for using only on simple tasks or so on, where I see a framework to compete with ASP.NET, for instance.

This mindset (where simple use-cases imply in developer need to do lots of "workarounds") is what takes the framework down, IMHO. And Telescope repository is probably one of the most representative of this mentality.

What makes me angry sometimes is that some of the problems are things that are closely related to Telescope's objective, like this issue here: is a use-case to log something that should be trivial (an application failure) for a project which the main purpose is to log/monitor failures - and it fails to handle it (at least without "workarounds"). Even considering this, contributors, in general, prefer to give "excuses" on why it works as it works than evolve the project to work as expected.

Sincerely, hope people working on this projects could perceive that Laravel (and its community) deserves better. Sorry for anyone who may feel sad about something in my comment, but I thought I should comment it anyway.

**Comment by justinkekeocha** [comment]
I understand your frustration, but to be honest, this is the first time I am experiencing workarounds like this. 

I wouldn't say the framework has a lot of workaround, I think laravel is well maintained. I would have submitted a PR to this, if I wasn't in a haste and if I didn't think this will introduce a breaking change.

@driesvints any input on this?

**Comment by luanmm** [comment]
@justinkekeocha I don't think is something of Laravel itself (this is why I'm comparing it with ASP.NET in the above comment), but it feels this way sometimes, mainly in "stallite project's" repositories.

Another example of situation where Laravel is underconsidered: https://github.com/laravel/telescope/issues/561. The answer for this other issue is "Laravel does not support installation in sub-directories". I understand why we should not expose files from Laravel root, but there is scenarios in big projects where the "sub-directory" is a reverse proxy mapping, that does not expose anything to the public. So, for micro-services scenarios, for instance, the answer to this other issue seems to be: "just don't use, because Laravel only supports small/trivial projects". And I just don't agree with this statement. Laravel is really better than this and I really think its contributors should "think bigger" sometimes.

Thanks for all your efforts, btw. What is implemented in Laravel/Telescope is really great. My criticism is only about what isn't or about what I think should be on the horizon - or, even more specific, on the mindset regarding what Laravel really is when feels like people underestimate it as a framework.
