### ISSUE TITLE
Client Request Watcher fails when there's a file upload (again)

### ISSUE THREAD

**Issue by rcerljenko** [laravel/telescope#1082]
- Telescope Version: 4.5.1
- Laravel Version: 8.49.2
- PHP Version: 7.4.21
- Database Driver & Version: MySQL 8.0.21

### Description:

Hi guys,

This is a followup on issue https://github.com/laravel/telescope/issues/1079 that's been fixed by the [4.5.1](https://github.com/laravel/telescope/pull/1080) release but it's actually not totally fixed.
Now I get the error message in the same file (`Watchers/ClientRequestWatcher.php`) on line 169 with a message: `filesize(): stat failed for <my-aws-s3-file-url>`

**Comment by driesvints** [comment]
Ping @gdebrauwer

**Comment by gdebrauwer** [comment]
@rcerljenko can you share a code example of the Http Client request you are executing?

**Comment by rcerljenko** [comment]
@gdebrauwer sure here it is:
```php
public function replaceFileOnProject(string $destFileUrl, string $srcFileUrl, array $data = [])
{
	$fileHandle = fopen($srcFileUrl, 'r');

	$data = Http::acceptJson()
		->withHeaders(['Content-Length' => ''])
		->attach('media', $fileHandle, pathinfo($srcFileUrl, PATHINFO_BASENAME))
		->patch($destFileUrl, $data);

	fclose($fileHandle);

	return $data->json();
}
```

**Comment by rcerljenko** [comment]
@gdebrauwer to give even more context here, both `$destFileUrl` and `$srcFileUrl` are public links to AWS S3 bucket files so this API call should just replace one with another...

**Comment by driesvints** [comment]
@gdebrauwer can you have another look at this?

**Comment by gdebrauwer** [comment]
I'm currently on vacation so I have not found the time yet to have a look at this issue 😞

**Comment by driesvints** [comment]
@gdebrauwer dont worry about it. Enjoy your vacation 🙂

**Comment by driesvints** [comment]
Hey @gdebrauwer. Have you found time yet to look into this?

**Comment by driesvints** [comment]
@rcerljenko I'll take a look myself. 

Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
@rcerljenko feel free to open a new issue once you'd provided a repo to reproduce this 👍
