### ISSUE TITLE
Frontend Request Polling Memory Leaks

### ISSUE THREAD

**Issue by myckhel** [laravel/telescope#1085]
- Telescope Version: v4.5.1
- Laravel Version: v8.49.0
- PHP Version: v8.0

### Description:
The frontend client does not stop request polling after leaving any watch section.

When i navigate from `Events` to `Jobs` section i expects `Events` request polling to stop but both `Events` and `Jobs` request polling continues.

![Screenshot 2021-07-05 at 13 08 40](https://user-images.githubusercontent.com/34090541/124469795-b5cce580-dd92-11eb-9755-8039c900c2f4.png)

### Steps To Reproduce:
- goto telescope dashboard
- navigate to `Events`, `Jobs`, `Queries`
- open developer console's network tab

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Sorry. Just read your issue.

Yes, this is the current behavior. Welcoming PR's that would update it.
