### ISSUE TITLE
Wrong "pending" Jobs status when using Laravel Horizon

### ISSUE THREAD

**Issue by ilyavaiser** [laravel/telescope#1113]
Telescope Version: v4.6.1
Laravel Version: v8.48.2
PHP Version: 7.4.22
Database Driver & Version:
Description:
Telescope shows pending status for jobs when using Horizon, even if the task is successful.

I am using Queued Laravel Notifications and they work great. The Horizon Dashboard displays the jobs information correctly. Notifications are sent to users. Everything is fine, but when I look at the list of jobs in Telescope, they are all displayed in the pending status.

I looked in Redis, there are no these jobs in pending status, the queue is empty.

Steps To Reproduce:
Create any Queues Notification Job and process it through Horizon

-----

https://github.com/laravel/telescope/issues/1111
https://github.com/laravel/telescope/issues/577
https://github.com/laravel/telescope/issues/507
https://github.com/laravel/telescope/issues/503
https://github.com/laravel/telescope/issues/411

Yes, I read the previous issues related to this problem and discussions on the support sites. Nothing helped.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.

**Comment by antoniovalenzuela** [comment]
https://github.com/laravel/telescope/issues/1331
