### ISSUE TITLE
$assetsAreCurrent is undefined

### ISSUE THREAD

**Issue by halimsupranata** [laravel/telescope#1115]
- Telescope Version: 4.6.1
- Laravel Version: 8.54.0
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8.0.26

### Description:
ErrorException
Undefined variable: assetsAreCurrent (View: /home/project/vendor/laravel/telescope/resources/views/layout.blade.php)

$assetsAreCurrent is undefined
Make the variable optional in the blade template. Replace {{ $assetsAreCurrent }} with {{ $assetsAreCurrent ?? '' }}

Stack trace in laravel Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/laravel/telescope/src/../resources/views/layout.blade.php:195 which is "<span>Queries</span>"

### Steps To Reproduce:
Open localhost/telescope and it will show the undefined variable error

**Comment by driesvints** [comment]
That was removed here: https://github.com/laravel/telescope/pull/1063. Most likely your assets aren't up to date. The best way to keep these assets up to date is by adding these lines to your composer.json file: 

https://github.com/laravel/laravel/blob/8.x/composer.json#L40-L42

**Comment by halimsupranata** [comment]
@driesvints It's not working. I still face the same problem
What I have try:
php artisan telescope:publish -> the vendor is publish but still not working
add this "@php artisan vendor:publish --tag=laravel-assets --ansi" ->the vendor is publish but still not working
php artisan view:clear -> not working
restart laptop -> not working

Still got $assetsAreCurrent is undefined

**Comment by driesvints** [comment]
This variable doesn't exists in Telescope anymore so you most definitely still have it in your code. Check your vendor directory and clear those assets manually if you need to.

**Comment by jay-knight** [comment]
```
$ php artisan telescope:publish
Publishing complete.
Copied Directory [/vendor/laravel/telescope/public] To [/public/vendor/telescope]
Publishing complete.
```

That doesn't overwrite `resources/views/vendor/telescope/layout.blade.php`. I copied the contents from [here](https://github.com/laravel/telescope/blob/5.x/resources/views/layout.blade.php) and it works.

**Edit:** I see now that we only have that file in our repo to override the default. If you just delete it you get the default telescope view. If you customized it, you'll need to redo your customization based on the new version, or otherwise update it to work with the new version of telescope.
