### ISSUE TITLE
New log name doesn't appear after making edit

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/telescope#1181]
- Telescope Version: 4.7.1
- Laravel Version: 8.82.0
- PHP Version: 7.4
- Database Driver & Version: SQL

### Description:

I've got a custom log channel called `Applications` in my website, I was previously logging as "Application submitted" but decided to change the title of the log. Upon deploying the change, Telescope appears to be continuing to read from the previous log name despite clearing out Telescope's data.

I'm not getting any errors to log, and I do have data set in my variables.

What am I missing to get the new log names to show up in the Telescope dashboard, for example:

> affiliate_full:foo,first_name:John - Application submitted

My method:

```php
/**
 * Store a newly created resource in storage.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return \Illuminate\Http\Response
 */
public function store(Request $request)
{
    try {
        $provider = new LES($request);
        $res = Http::timeout(120)->post(
            $provider->getSubmitEndpoint(),
            $provider->getMappedApplicationToSubmit()
        );
    } catch (\Exception $e) {
        return response()->json([
            'message' => "Mapping failed"
        ], 422);
    }

    try {
        $affiliate_full = $request->input('meta.affiliate_full') ?? 'unknown';
        $first_name = $request->input('applicant.first_name') ?? 'unknown';

        Log::channel('applications')->info("affiliate_full:$affiliate_full,first_name:$first_name - Application submitted", [
            'provider' => 'LES',
            'submitted_endpoint' => $provider->getSubmitEndpoint(),
            'submitted_application_raw' => $request->all(),
            'submitted_application_mapped' => $provider->getMappedApplicationToSubmit(),
            'submitted_at' => Carbon::now(),
            'raw_res_json' => $res->json(),
            'raw_res_status' => $res->status()
        ]);
    } catch (\Exception $e) { }

    return response()->json($res->json(), $res->status());
}
```

My channel:

```php
'channels' => [
    'applications' => [
        'driver' => 'daily',
        'path' => storage_path('logs/applications/applications.log'),
        'level' => 'info',
        'days' => 7
    ],
],
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
I'll re-open this as soon as you've provided a repository. Thanks
