### ISSUE TITLE
Eloquent Model creation assigning ID=0 

### ISSUE THREAD

**Issue by George-nacouzi** [laravel/telescope#1344]
### Telescope Version

4.4

### Laravel Version

9.52.7

### PHP Version

8.1.18

### Database Driver & Version

 MySQL 8.0

### Description

After updating laravel from version 8.x to 9.x, 

```
$model = Model::create([...]);
$model->id; // this returns 0
```

While in the database the id is correct but the model assigned id is equal to 0.

When i disable the `QueryWatcher` in `config/telescope.php` the id is returned correctly 

This same issue was raised in 2018 and solved [here](https://github.com/laravel/telescope/issues/289)

I removed the vendor folder and deleted composer.lock then ran `composer update` but the issue persisted.

### Steps To Reproduce

after updating from laravel 8.x to laravel 9.x, when using `Model::create()`  the id returned is always 0 unless you disable the `QueryWatcher` from the `config/telescope.php`

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by nunomaduro** [comment]
Could you please confirm that you are using the most recent version of Telescope and that your configuration file is up-to-date? You can obtain the configuration file at https://github.com/laravel/telescope/blob/4.x/config/telescope.php.

In a previous time a user had this issue, it was resolved by updating their configuration file. If thi solves your problem, kindly notify me so that we can add it into the upgrade guide. If it does not solve the issue, please let me know so that we can re-open this issue.

**Comment by mrriddwan** [comment]
No, it's still here unfortunately.

**Comment by mrriddwan** [comment]
Yes, it's still here. When disable the query watcher, it works.

**Comment by goldmerc** [comment]
I just ran into this issue and updating the config/telescope.php file to match the latest release worked for me.

**Comment by Alfonsinjo** [comment]
Same for me - I updated the config file and tried to use telescope again but it didnt work. I always get 0 back, if i check the last inserted id. (I updated to version : * v5.0.4, and also changed the config file)
