### ISSUE TITLE
Pause button not working

### ISSUE THREAD

**Issue by travisricks** [laravel/telescope#1370]
### Telescope Version

4.15.2

### Laravel Version

10.17.1

### PHP Version

8.1.17   

### Database Driver & Version

MySQL 8.0.23

### Description

Hello, just started using Telescope (local only) and I'm not sure if this is a bug or I've set something up incorrectly.

When I click the pause recording button, I see a successful POST call in the network tab, but then calls to the `requests` endpoint continue and data is still added to the table. I do not have the 'auto load entires' button selected.

![Screenshot-001991-2023-08-09at10 39 04](https://github.com/laravel/telescope/assets/289841/174734d4-e784-4447-a824-b1d82d01eac5)

I looked through past issues but only found this: https://github.com/laravel/telescope/issues/994. Since there are no other bug reports, it makes me think it's a configuration issue on my end. Any suggestions for troubleshooting this?

Thanks!

### Steps To Reproduce

1. go to Telescope dashboard
2. click pause recording

EXPECTED: no new data is loaded into the requests table
ACTUAL: data is continuing to load

**Comment by crynobone** [comment]
Can you share the output of `requests?tag=&take=1&...`?

![CleanShot 2023-08-09 at 12 30 35](https://github.com/laravel/telescope/assets/172966/0aef3222-1b82-40c9-b01a-c87c861049a6)

On my side, I would see that it still showing `paused`. The requests still going through do make sense in a way because the `pausing` cache is global and it can be unpaused by other users accessing Telescope or the command line.

**Comment by travisricks** [comment]
I'm seeing enabled after the toggle-recording endpoint is called.

![Screenshot-002000-2023-08-09at21 26 09@2x](https://github.com/laravel/telescope/assets/289841/666c2b07-b7d9-43ae-a8ee-99260872fc18)

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by travisricks** [comment]
Thanks for the help. I'm only using this locally so it's not really a blocker and I'm sure it's an issue on my end. I'll close this for now.
