### ISSUE TITLE
  Telescope doesn't record jobs or mails when I am using dispatchafterresponse()  on database queue for sending emails

### ISSUE THREAD

**Issue by dev-mo-ali** [laravel/telescope#1381]
### Telescope Version

4.16.1

### Laravel Version

10.2.0

### PHP Version

8.1.0

### Description

I am using the queue database to send emails 
evn production 
 noticed it Telescope doesn't record jobs or mails when I am using dispatchafterresponse()
but is it working with dispatch()

How to show the jobs and sent emails in Telescope when using:  dispatchafterresponse()

### Steps To Reproduce

How to show the jobs and sent emails in Telescope when using:  dispatchafterresponse()

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
