### ISSUE TITLE
Gate::define callback doesn't run

### ISSUE THREAD

**Issue by N3OGeorgy** [laravel/telescope#1414]
### Telescope Version

4.17.2

### Laravel Version

10.33.0

### PHP Version

8.1

### Description

When in production mode and debug turned off, the `Gate::define` does not run.
I need to mention that i don't have any authentication package installed and i'm using Laravel Octane v2.1.1 ( if matters ).

The `TelescopeServiceProvider.stub` contains following method: 
```php
    protected function gate(): void
    {
        Gate::define('viewTelescope', function ($user) {
            return in_array($user->email, [
                //
            ]);
        });
    }
```

As mentioned in #1329 replacing `function ($user)` with `function (?User $user)` will allow running the `viewTelescope` callback contents.

### Steps To Reproduce

1. Install fresh laravel app and telescope package
2. run `php artisan telescope:install`
3. Put app into production
4. Add a `logger()->info('pass')` inside `Gate::define` callback
```php
Gate::define('viewTelescope', function ($user) {
    logger()->info('pass');
    return in_array($user->email, [
        //
    ]);
});
```
5. Check if log is written after accessing `/telescope` route

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by bibrokhim** [comment]
> As mentioned in #1329 replacing `function ($user)` with `function (?User $user)` will allow running the `viewTelescope` callback contents.

That's how it should be.
For unauthenticated users, laravel skips the callback function and immediately returns false. You must make user nullable to allow authorization checks.

Here's what documentation says:
[https://laravel.com/docs/10.x/authorization#guest-users](https://laravel.com/docs/10.x/authorization#guest-users)

> By default, all gates and policies automatically return false if the incoming HTTP request was not initiated by an authenticated user. However, you may allow these authorization checks to pass through to your gates and policies by declaring an "optional" type-hint or supplying a null default value for the user argument definition

**Comment by driesvints** [comment]
Thanks @bibrokhim
