### ISSUE TITLE
Telescope not record any entry fpr laravel abort method

### ISSUE THREAD

**Issue by redfieldchristabel** [laravel/telescope#1481]
### Telescope Version

latest

### Laravel Version

11

### PHP Version

Php - FPM latest (Docker)

### Database Driver & Version

Mysql Latest (Docker)

### Description

I have used many abort methods in my project, but none (I think) of them are recorded by telescope. the response returns a stack trace since I'm still in local but the telescope shows nothing (Just Empty Space). Do I install it not correctly or do I need to register any service to make it work with abort? We use Laravel for the headless system, so we depend on the telescope.

it only records for return types like 422 by Laravel default validation process, Gate authenticates, and all return responses, but not with the abort method. I read some about the Laravel abort method, which throws a HttpExeptopn instance. so I don't think abort is not a best practice style. that is why I am asking this question.

![image](https://github.com/laravel/telescope/assets/69151253/e7445e91-839b-4a6a-8e9c-812917157362)

### Steps To Reproduce

install telescope as mentioned in the official doc, (not with local only, normal version).
use the abort method on any controller. (some of mine on model).
Trigger that request, (I use postman and flutter).
Telescope not record that request.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
