### ISSUE TITLE
Artisan::output() - no output

### ISSUE THREAD

**Issue by pszucs** [laravel/telescope#151]
After installing Telescope the Artisan::output() calls return nothing (empty string).

Example:
```php
Artisan::call('route:list');

dd(Artisan::output());
```
Output:
```php
""
```

After removing the laravel/telescope package the Artisan::output() returns the expected output.

The contents of the BufferedOutput (`$output` variable) seems to be disappearing after firing the `Events\CommandStarting` or `Events\CommandFinished` event (not sure) in the `Illuminate\Console\Application::run` method:

```php
$this->events->fire(
    new Events\CommandFinished($commandName, $input, $output, $exitCode)
);
```

**Comment by ybaruchel** [comment]
This happens beacuse you can't call the `Artisan::output()` twice and Telescope [calls it](https://github.com/laravel/telescope/blob/1.0/src/Watchers/CommandWatcher.php#L40).

That's because Telescope [make use of the output() method](https://github.com/laravel/telescope/blob/1.0/src/Watchers/CommandWatcher.php#L40) for getting the last command output which uses symfony's console `BufferedOutput` that empties buffer and returns its content, so the next time you call it it will be empty.

**Comment by pszucs** [comment]
@ybaruchel Ah I see, thanks for the explanation.
