### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by pajkho** [laravel/telescope#1546]
### Telescope Version

5.2

### Laravel Version

10.44

### PHP Version

8.2

### Description

If you have a very large json content, line 183 in RequestWatcher will throw an "Allowed memory size of XXX bytes exhausted".

Could this be solved by checking the contentWithinLimits before trying to json_decode? Something along the lines of below code. Let me know if I should do a PR for this.

```
if (is_string($content)) {
    // Check if content is JSON and within size limits
    if ($this->contentWithinLimits($content) && 
        is_array(json_decode($content, true)) && 
        json_last_error() === JSON_ERROR_NONE) {
        return $this->hideParameters(json_decode($content, true), Telescope::$hiddenResponseParameters);
    }

    // Check for plain text content type
    $contentType = strtolower($response->headers->get('Content-Type') ?? '');
    if (Str::startsWith($contentType, 'text/plain')) {
        return $this->contentWithinLimits($content) ? $content : 'Purged By Telescope';
    }
}
```

### Steps To Reproduce

Make a very large json response in a request.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
