### ISSUE TITLE
Call query multiple times when telescope is enabled

### ISSUE THREAD

**Issue by FaisalBudiono** [laravel/telescope#1549]
### Telescope Version

5.2.5

### Laravel Version

11.32.0

### PHP Version

8.3.13

### Database Driver & Version

Postgres:16-alpine3.2 (dockerized)
> Also tried with Mysql 8.2, the conclusion still the same

### Description

When I try to test my API that has `auth()->user()` method called, it will do "search query" multiple times for some reason. The weird thing is the query is called more than 1000 times and it takes more than 10 second for the request to resolved, If I disable the telescope, the request only took sub 100ms.

See the image below for the snippet.

![image](https://github.com/user-attachments/assets/de1228eb-49dc-49ad-9b0b-7dc91fd3858d)

### Steps To Reproduce

1. Install laravel/telescope
2. Configure telescope in local only (like what being told in the official documentation)
3. Try hit the API that has `auth()->user()` on it
4. The telescope will report that the request has more than 1000 API call

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
