### ISSUE TITLE
Cache driver change on migration

### ISSUE THREAD

**Issue by AbdelkaderBah** [laravel/telescope#196]
I change the value of ```Default Cache Store``` in "cache.php" to ```database``` then tried to run this command which create a migration for the database cache php artisan cache:table 

Error message:
 ``` Base table or view not found: 1146 Table 'bugtracker.cache' doesn't exist (SQL: select * from `cache` where `key` = laravel_cachetelescope:dump-watcher limit 1)```

**Comment by ybaruchel** [comment]
Hi @AbdelkaderBah 
Please follow the next steps:

1. Change your cache driver to file (`CACHE_DRIVER=file` on your `.env` file)
2. Run the `php artisan cache:table` command
3. Restore your cache driver to database (`CACHE_DRIVER=database` on your `.env` file)

The problem is that you have the dump watcher enabled (on your `telescope.php` config file) and it tries ([here](https://github.com/laravel/telescope/blob/aedd2e23a1d451d46124e3c681f68a75defae203/src/Watchers/DumpWatcher.php#L43)) to get cached dumps from the database (since it's your default cache driver) but the cache table doesn't exist.

**Comment by AbdelkaderBah** [comment]
@ybaruchel thanks, I know exactly the cause. I just wanted to notice about this issue.

People now can reference from your comment to solve the issue.
