### ISSUE TITLE
css don't works

### ISSUE THREAD

**Issue by jonuran** [laravel/telescope#293]
hi,

when I go to my project

http://localhost/laravel/public/telescope

css don't work 

![captura1](https://user-images.githubusercontent.com/8787831/47831350-f3ba1600-dd6e-11e8-9813-795caf489e7b.PNG)

**Comment by themsaid** [comment]
Make sure you've published the assets and check your browser console errors.

**Comment by souvikBullet** [comment]
I have also css design problem..same view is coming when run in staging server..
it says..

Resource interpreted as Stylesheet but transferred with MIME type text/html:  as an error


now what have to do?

**Comment by asmit99nepali** [comment]
I got the same error, how to fix any solution ?

**Comment by Mirmuxsin** [comment]
I've faced with that issue 2-3 times when I deployed my project to production server

The problem was that I'vent set ASSET_URL in my .env which called in config/app.php
That's why laravel telescope was doing http requests to load css file instead of https when my server was accepting only https.

Solution:
Just set your ASSET_URL in your .env like https://domain.com

**Comment by jovialcore** [comment]
> I've faced with that issue 2-3 times when I deployed my project to production server
> 
> The problem was that I'vent set ASSET_URL in my .env which called in config/app.php That's why laravel telescope was doing http requests to load css file instead of https when my server was accepting only https.
> 
> Solution: Just set your ASSET_URL in your .env like https://domain.com

God bless you
