### ISSUE TITLE
[Feature Request] Timeline

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/telescope#335]
I think timeline would be a key feature to have like the ones that exist in Laravel Debugbar and Symfony Debug Toolbar

<img width="584" alt="screen shot 2018-11-05 at 10 19 51 pm" src="https://user-images.githubusercontent.com/16099046/48013518-7e718b00-e14a-11e8-9fdf-b9a92a94dc87.png">

![16958066809_c25c9db712_o](https://user-images.githubusercontent.com/16099046/48013590-ab25a280-e14a-11e8-9fb2-452ee2d38b0c.png)

Would like to hear others' views on whether this may be useful and if yes, what would be the ideal segments/stop points to measure. If this is a popular request, I might be able to find some time to work on this.

**Comment by DonovanChan** [comment]
A hundred times yes to this. Debugbar is great but not very useful when beginning to troubleshoot application performance. I've been playing with xDebug profiling and qcachegrind but it's difficult to make sense of compared to the timeline example above. Tideways is also out of the question because we can't send any data offsite and can't get anything parsing its local output correctly.

As someone new to profiling, a basic timeline by runtime would be very helpful for spotting bottlenecks.

**Comment by winter-ice** [comment]
THIS FEATURE IS VERY HELPFUL!

**Comment by themsaid** [comment]
Feel free to open a PR so we can discuss the implementation :)

**Comment by mvehar** [comment]
Any fololow-up on this one?

**Comment by Forsakenrox** [comment]
> Any follow-up on this one?

Taylor dismissed the PR of @barryvdh which contained a clean and simple implementation of this highly requested feature 4 years ago and suggested using Blackfire. Why not for example clockwork is a big mystery. I concluded for myself that Taylor does not want this function in this library. Considering 4 year pass away, and still no any movement in this vector.
