### ISSUE TITLE
How to properly uninstall Telescope?

### ISSUE THREAD

**Issue by ckissi** [laravel/telescope#361]
How to uninstall telescope? After updating to new version I'm getting this error:

`Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::getOriginalContent()`

Here:
```
Symfony\Component\Debug\Exception\FatalThrowableError 
…/vendor/laravel/telescope/src/Watchers/RequestWatcher.php 115
```

Line 115 contains this:
`$originalContent = $response->getOriginalContent();
`

**Comment by paras-malhotra** [comment]
To uninstall, you can just add TelescopeServiceProvider in `dont-discover` and remove your app's TelescopeServiceProvider from `config/app.php`.

The issue that you're referring to has been fixed in https://github.com/laravel/telescope/commit/e4f5c0dd07970fb73fbf79cfa96316b7f91560cf and will be available in the next release.

**Comment by ckissi** [comment]
Thank you!

**Comment by rockfreak** [comment]
If you just want to disable it and not remove it for some reason or another then you should actually put the package name in the dont-discover array and run `composer dump` to re run the autoload scripts

```
"extra": {
        "laravel": {
            "dont-discover": ["laravel/telescope"]
       }
},
```
