### ISSUE TITLE
Publish assets with Composer hook

### ISSUE THREAD

**Issue by driesvints** [laravel/telescope#594]
Like https://github.com/laravel/horizon/issues/554 it should also be possible for Telescope to publish updated assets after a composer dependency update. Telescope will need to add its own assets command for this.

**Comment by barryvdh** [comment]
An alternative to this could be:
 - Render the assets inline (downside: no caching, loaded each request but not so big an issue because it's loaded only on the first request)
 - Pass the assets through the API (eg `/telescope/assets/script.js` -> AssetController@getScriptJs`, which could set a TTL for browser caching)
