### ISSUE TITLE
Duplicate Query Indication

### ISSUE THREAD

**Issue by JonPurvis** [laravel/telescope#603]
Apologies in advance if it already exists and I've just missed it. I was wondering if it's possible to have an indication of duplicate queries in the list of queries when viewing a request. It'd just make it easier to see at a glance which ones are duplicates.

**Comment by danilopolani** [comment]
I don't think currently there's a way, also because of the way data is saved in `telescope_entries` it could be a bit tricky. Because MySQL introduced `REGEXP_SUBSTR` only since 8.0, a valid but not precise (it doesn't include query bindings) query to achieve it also from previous versions could be:

### TL;DR:

Use the query after the line and there you go. I think it would take a bit of time to implement this on Telescope because of displaying single query detail / expand the aggregated data.

### LR:

```
SELECT
	COUNT(sequence) AS cnt,
	SUBSTRING_INDEX(SUBSTRING_INDEX(content, '"sql":"', -1), '","time":', 1) AS q
FROM telescope_entries
	WHERE type = 'query'
GROUP BY q
ORDER BY cnt DESC
```

Just to explain the query a bit:

- In the `telescope_entries` table, queries are stored in a JSON with the key `sql`. With `SUBSTRING_INDEX(content, '"sql":"', -1)` we get the content from the first apis opening the query (like `"sql":"select * from ...",`) to the end of the JSON. With `-1` you get the "right content" of the matching part.
- With the second substring - `SUBSTRING_INDEX(.., '","time":', 1)`, we get the content from `","time":`  , namely the key after `sql`, to the _start_ of the JSON (in this case, the query itself). With `1` instead of `-1` we get the "left content" of the match.
- Finally, with `WHERE type = 'query'` we get only query logs (because there may be also requests, cache, redis etc.) 

The rest is just common MySQL stuff like `GROUP BY`, `COUNT` and so on. I know I didn't explain it very well, but trust me haha. 

----

We can also recycle the logic above used to extract the query, to extract the bindings and, merging everything together, we can get a query to have real unique queries counter:

```
SELECT
	COUNT(sequence) AS cnt,
	CONCAT(
		SUBSTRING_INDEX(SUBSTRING_INDEX(content, '"bindings":', -1), ',"sql":', 1), # extract bindings
		'::', # just a fancy separator, maybe to change for performance?
		SUBSTRING_INDEX(SUBSTRING_INDEX(content, '"sql":"', -1), '","time":', 1) # extract query
	) AS full_query
FROM telescope_entries
	WHERE type = 'query'
GROUP BY full_query
ORDER BY cnt DESC
```

Maybe this could be a starting point for a future feature on Telescope, it would involve also adding a "full log" when you "inspect" a record and this could take a bit of time, because currently a single record is shown by its UUID, like `http://localhost/telescope/queries/8d58bbda-5470-4dc2-b7c6-bf9d66e62c40`.  
They should retrieve the output of `full_query` above and find all queries matching that value, displaying a list and, on click, expand detail (both on generic listing or detail view page).  

What do you think @themsaid ?

**Comment by themsaid** [comment]
Feel free to open a PR. thanks :)

**Comment by barryvdh** [comment]
I think we only need to store the familyHash (like in Exceptions) of the unprepared query (eg. what we already get from the Event). By storing that unprepared query, you can count the number of instances of queries like (`where user_id = 1`, `where user_id = 2` etc). 
I've made this as part of https://github.com/laravel/telescope/pull/706 but the actual counting of the duplicates need to be done still.

**Comment by tillkruss** [comment]
@barryvdh: Are you up for a PR?

**Comment by barryvdh** [comment]
That was done in https://github.com/laravel/telescope/pull/706

**Comment by tillkruss** [comment]
Ah, cool! Is there any way to highlight the duplicates? I can’t identify them easily, because of the truncating.

**Comment by barryvdh** [comment]
What would be the best way to highlight them? Highlight everything with > 1 queries, or highlight the same queries on hover?
They can be identified using the familiyHash property.

**Comment by tillkruss** [comment]
Hover might be an issue on touchscreens and go outside the viewport. 

A badge/tag is probably good?

**Comment by dotus-ru** [comment]
"laravel/telescope": "^2.1" not show all duplicate query, only latest 
Telescope: 4 queries
select * from `customers` where `customers`.`company_id` = 5
select * from `companies` where `companies`.`id` = 2 limit 1
select * from `companies`
select * from `customers`

Debug Bar: 22 queries (22 statements were executed, 15 of which were duplicated, 7 unique)
select * from `customers`
select * from `companies`
select * from `customers` where `customers`.`company_id` = 1
select * from `customers` where `customers`.`company_id` = 2
select * from `customers` where `customers`.`company_id` = 3
select * from `customers` where `customers`.`company_id` = 4
......

**Comment by barryvdh** [comment]
On the index page or on the request page?

**Comment by barryvdh** [comment]
Ah yeah they are filtered on familyHash: https://github.com/laravel/telescope/blob/1de5ecb6c483820d4bcd86452240653bdb1b992d/resources/js/components/IndexScreen.vue#L122
But there is no way to see the related items like on the Exceptions page.

**Comment by dotus-ru** [comment]
> On the index page or on the request page?
/telescope/queries page

**Comment by barryvdh** [comment]
@dotus-ru I've submitted a fix in https://github.com/laravel/telescope/pull/773
