### ISSUE TITLE
419 HTTP status code

### ISSUE THREAD

**Issue by ForzaSFerrari** [laravel/telescope#64]
In one project where I use Laravel Passport I'm faced with the 419 HTTP status code. In my database I can see that all entries are saved, but I only get to see that the api entries of telescope will be scanned in the view. Nothing else happens.

**Comment by themsaid** [comment]
I don't understand what you mean, please explain more and share screenshots, where do you get the 419  response?

**Comment by ForzaSFerrari** [comment]
That's the view on every telescope page.
![telescope_scanning](https://user-images.githubusercontent.com/16107131/47387622-3006ca00-d710-11e8-97c0-08709494e922.PNG)

That's says the browser.
![telescope_419_api_edit](https://user-images.githubusercontent.com/16107131/47387841-cd61fe00-d710-11e8-91fd-6d1ecf1bade4.png)

**Comment by ForzaSFerrari** [comment]
If I add telescope to the VerifyCsrfToken file of the Laravel framework, then I get all telescope entries from the database to see. But is this the optimal solution?

**Comment by lsfiege** [comment]
I've experienced this issue in #34 , my solution was update the `Http/Kernel.php` file so that it corresponds with the latest version and have also added missing Middlewares in my app. Maybe you have a similar problem

**Comment by derekmd** [comment]
## Likely Laravel Framework fix

`Illuminate\Foundation\Http\Middleware\VerifyCsrfToken` and `EncryptCookies` should be changed to never PHP serialize the CSRF token.

## Explanation

I believe it's a framework problem caused by PHP serialization in the `X-XSRF-TOKEN` cookie used by Telescope's Ajax request.

**Illuminate\Foundation\Http\Middleware\VerifyCsrfToken@getTokenFromRequest()**

```php
protected function getTokenFromRequest($request)
{
    $token = $request->input('_token') ?: $request->header('X-CSRF-TOKEN');

    if (! $token && $header = $request->header('X-XSRF-TOKEN')) {
        $token = $this->encrypter->decrypt($header, static::serialized());
    }

    return $token;
}
```

`static::serialized()` in that decrypt call is _always_ `false` even if your application's middleware asks for cooke PHP serialization.

i.e., status code 419 comes from these hashes being compared by the `VerifyCsrfToken` middleware:

* `'YHOOALqzvSbuzQQVurmTpQJM5NaVArIgoEStYrgd'`
* `'s:40:"YHOOALqzvSbuzQQVurmTpQJM5NaVArIgoEStYrgd'`

https://laravel.com/docs/5.6/upgrade "Configuring Cookie Serialization"

It's suggested to make this change:

**App\Http\Middleware\EncryptCookies**

```php
protected static $serialize = true;
```

`App\Http\Middleware\VerifyCsrfToken::serialized()` is pulling the base `Illuminate\Cookie\Middleware\EncryptCookies::$serialize = false` rather than the documented `App\Http\Middleware\EncryptCookies$serialize = true` override.

## App-level fix

Instead of  `protected static $serialize = true;` as suggested by the 5.6 upgrade guide, override the `serialized()` method and don't serialize the CSRF token:

```php
class EncryptCookies extends BaseEncrypter
{
    public static function serialized($name)
    {
        return $name !== 'XSRF-TOKEN';
    }
}
```

## Framework fix

Never PHP serialize the CSRF token since this hasn't been working since August and nobody complained about it until now. It doesn't really make any sense to serialize short-lived tokens (~3 hours?) that are just PHP strings? Anyone still serializing cookies are for complex (array, object) with a long time-to-live.

## Why hasn't anyone noticed this problem in Laravel?

Because the stragglers still PHP serializing cookies probably use Blade `@csrf` / `request('_token')` to pass CSRF tokens across requests. In that case, `VerifyCsrfToken@getTokenFromRequest()` short-circuits the buggy conditional.

**Comment by pactode** [comment]
**Laravel Version: v5.7.10**

I'm getting this error as well. My `\App\Http\Kernel` along with the middlewares are identical to the ones in a fresh Laravel installation. It is caused by the `\App\Http\Middleware\VerifyCsrfToken` as @derekmd mention above.

In order to get Telescope to work, I have to add the telescope endpoints to the `\App\Http\Middleware\VerifyCsrfToken` middleware, like this:
```php
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '/telescope/*',
    ];
```

Let me know if you know a way to fix this.

**Comment by ForzaSFerrari** [comment]
For me it's been fixed.

**Comment by bendadamohamed** [comment]
go to Kernel.php file and comment this line :
          `  // \App\Http\Middleware\VerifyCsrfToken::class,`

**Comment by hallowcard13** [comment]
> **Laravel Version: v5.7.10**
> 
> I'm getting this error as well. My `\App\Http\Kernel` along with the middlewares are identical to the ones in a fresh Laravel installation. It is caused by the `\App\Http\Middleware\VerifyCsrfToken` as @derekmd mention above.
> 
> In order to get Telescope to work, I have to add the telescope endpoints to the `\App\Http\Middleware\VerifyCsrfToken` middleware, like this:
> 
> ```
>     /**
>      * The URIs that should be excluded from CSRF verification.
>      *
>      * @var array
>      */
>     protected $except = [
>         '/telescope/*',
>     ];
> ```
> 
> Let me know if you know a way to fix this.

Works for me thank you, my only concern is that, does it make some kind of open door for attackers ?

**Comment by Paradiddley** [comment]
I just came across this issue myself and this might fix it without having to exclude Telescope from CSRF checks or disabling CSRF altogether, which is definitely **not** what you want to do.

Check if you have `SESSION_DOMAIN` set in your .env. Whatever domain that's set to will need to be used to access Telescope as the `XSRF-TOKEN` cookie includes the domain if that env var exists. Without the env var altogether should work. Also if `SESSION_DOMAIN` and `TELESCOPE_DOMAIN` mismatch then this will also cause the 419 CSRF error.

@hallowcard13 it should be fine using @pactode's solution if you have configured Telescope for local environments only. If you're using it for production too then you're right to be cautious if you're using Laravels auth to gain access to it.

**Comment by sultanleth** [comment]
> > **Laravel Version: v5.7.10**
> > I'm getting this error as well. My `\App\Http\Kernel` along with the middlewares are identical to the ones in a fresh Laravel installation. It is caused by the `\App\Http\Middleware\VerifyCsrfToken` as @derekmd mention above.
> > In order to get Telescope to work, I have to add the telescope endpoints to the `\App\Http\Middleware\VerifyCsrfToken` middleware, like this:
> > ```
> >     /**
> >      * The URIs that should be excluded from CSRF verification.
> >      *
> >      * @var array
> >      */
> >     protected $except = [
> >         '/telescope/*',
> >     ];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if you know a way to fix this.
> 
> Works for me thank you, my only concern is that, does it make some kind of open door for attackers ?

the best answer, it works with me

**Comment by y8a5y** [comment]
For people still having this issue, here the quickest fix with the new app bootstrapping structure.

In `bootstrap/app.php`, simply add:

```diff
  ->withMiddleware(function (Middleware $middleware) {
+     VerifyCsrfToken::except('telescope/*');
  })
```

Hope it helps.
