### ISSUE TITLE
GateWatcher requires Authenticable instead of Authorizable

### ISSUE THREAD

**Issue by CiiDyR** [laravel/telescope#787]
- Telescope Version: 2.1
- Laravel Version: 6.6.0
- PHP Version: 7.3.4

### Description:
There are cases where you have models that only implement the Authorizable contract and not also the Authenticable contract. If you need a pivot model to scope permissions to a group for example, you might only want authorization capabilities and nothing more. The GateWatcher is not able to record these cases and there will be an exception.
I think it makes more sense to require an Authorizable there.

### Steps To Reproduce:
Create a regular model, apply
```php
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Foundation\Auth\Access\Authorizable;
```

and finally try to use the ```can``` method on an instance of that model with the GateWatcher enabled.

What are your thoughts on this?

**Comment by driesvints** [comment]
I'll leave this up to @themsaid to determine if this is a bug or enhancement.

**Comment by themsaid** [comment]
@CiiDyR  can you share more details? I don't understand what the issue is?

**Comment by CiiDyR** [comment]
Of course. Currently the GateWatcher requires an ```Authenticatable``` to be passed to the ```recordGateCheck``` method. This is fine if you use it with a more common scenario where you probably have permissions only associated with Models that actually are an ```Authenticatable```.
In my case I have a regular/pivot model that doesn't have to be authenticated, but has permissions associated with it.

Say you have a user that is part of multiple teams (that can also have multiple users / think many-to-many here). This user has different roles in different teams. I applied the trait and contract I was talking about in my initial comment to the pivot model that actually has the role associated to it.
The pivot of course doesn't need authentication functionality, just authorization.
As soon as you use the ```can``` method on any instance of that pivot there will be an exception as the ```GateWatcher``` requires ```Authenticatable``` or ```null```.

See: https://github.com/laravel/telescope/blob/2.0/src/Watchers/GateWatcher.php#L37

**Comment by themsaid** [comment]
But the model that the gate expects should implement Authenticatable. That's is expected in different parts of Gate.php

**Comment by sebdesign** [comment]
@driesvints @themsaid I'm facing the same issue, using the Gate against another model that implements the `Authorizable` instead of the `Authenticatable` contract.

The Gate indeed expects an instance `Authenticatable`, but this contract is not being enforced anywhere, because it doesn't use **any**  of the `Authenticatable` methods, and this interface is declared in the docblocks and **not** as a typehint.

- The `canBeCalledWithUser()` method expects `Authenticatable|null` but only checks if the `$user` is `null` or not. Even the `parameterAllowsGuests()` doesn't care about the class of the `$user`, as long as it's typehinted.
- The `callAuthCallback`, `callBeforeCallbacks()`, `resolveAuthCallback()`, `callPolicyMethod()` methods expect `Authenticatable|null` but they are passing the `$user` to other methods/functions.
- The `callAfterCallbacks()`, `resolvePolicyCallback()`, `callPolicyBefore()` methods expect `Authenticatable` (but not null for some reason), but they are passing the `$user` to other methods/functions.
- The `forUser()` method expects `Authenticatable|mixed` and passes the `$user` within a closure for the `userResolver` callback. This method is called in the `can()` method of the `Authorizable` trait that implements the `Authorizable` contract, but this instance is not always an `Authenticatable`.

So practically the Gate doesn't care at all about the instance of the `$user`, it only checks if it's `null` for guest users.
On the other hand the `GateWatcher` enforces the `$user` to be `Authenticatable|null`, which is not compatible with the Gate.

Ideally the Gate should expect `Authorizable|null` in its method parameters, even if doesn't enforce it, and that would be nice if that was changed in Laravel 8.

But for now the solution would be to remove the `?Authenticatable` typehint and only use the `Authenticate|null` docblock parameter like the Gate does. After all the `$user` parameter is not even used in the `recordGateCheck()` method.

**Comment by mr-mmmmore** [comment]
I am facing the same issue when using the `can` method on a model that implements `Authorizable` but not `Authenticatable`. It has been working like this for years in my app but now Telescope's `GateWatcher` breaks it. 

The `can` method is in the `Authorizable` trait and I think it should work wether the model is an `Authenticatable` or not. These contracts are separate for a reason and it seems that the `GateWatcher` ties them when it shouldn't.

**Comment by mr-mmmmore** [comment]
I think this issue should be reopened.

**Comment by JoeZing** [comment]
> 

Yep,I agree with your point, I have the same problem that in my project all the models are extends a `BaseModel`,the $user is not a type of `Authenticatable `
