### ISSUE TITLE
Laravel Telescope faile to install it throws error

### ISSUE THREAD

**Issue by kamalhappysanz** [laravel/telescope#844]
**Problem 1**

    **- Conclusion: remove laravel/framework v5.8.37
    - Conclusion: don't install laravel/framework v5.8.37
    - laravel/telescope 3.x-dev requires laravel/framework ^6.0|^7.0 -> satisfiable by laravel/framework[6.x-dev, 7.x-dev].
    - laravel/telescope v3.1.0 requires laravel/framework ^6.0|^7.0 -> satisfiable by laravel/framework[6.x-dev, 7.x-dev].
    - laravel/telescope v3.1.1 requires laravel/framework ^6.0|^7.0 -> satisfiable by laravel/framework[6.x-dev, 7.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, v5.8.37].
    - Can only install one of: laravel/framework[7.x-dev, v5.8.37].
    - Installation request for laravel/framework (locked at v5.8.37, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.37].
    - Installation request for laravel/telescope ^3.1 -> satisfiable by laravel/telescope[3.x-dev, v3.1.0, v3.1.1].
Installation failed, reverting ./composer.json to its original content.**

**Comment by knightus** [comment]
Since Telescope 3.0.0 drop the support for Laravel 5.8 (https://github.com/laravel/telescope/releases/tag/v3.0.0), if you're sticking with Laravel 5.8.37, the latest telescope version that compatible is v2.1.7. You have to specify that in your composer require command, or in your composer.json file before installing.

If you want to use the latest telescope version, you will have to upgrade Laravel to v6 or v7 first
