### ISSUE TITLE
Unable to run the post-install-cmd when in non-dev install environment

### ISSUE THREAD

**Issue by ragingdave** [laravel/telescope#948]
- Telescope Version: 3.5.1
- Laravel Version: 7.28.1
- PHP Version: 7.4.3

### Description:
When using telescope for only certain environments, but using the telescope:publish command as part of composer post-update-cmd, the call fails even using error suppression, and the composer install/update fails as a result with the following error:

There are no commands defined in the "telescope" namespace.

### Steps To Reproduce:
Install telescope into an app using, https://laravel.com/docs/7.x/telescope#installation specifically the "Installing Only In Specific Environments" steps.
Using the further documented steps to ensure that you keep the assets up to date:https://laravel.com/docs/7.x/telescope#upgrading-telescope as a post-update-cmd
After Running an initial composer install to ensure a lock file exists, then run composer install using the `--no-dev` switch and see that composer install/update fails with the above mentioned error and will not actually complete.

**Comment by paras-malhotra** [comment]
@ragingdave `post-update-cmd` scripts are run when either `composer update` is run or `composer install` is run without a lock file. Both situations shouldn't happen in production because it's recommended to commit your `composer.lock` file in your projects and not run `composer update` on production.

If however, for some reason, you aren't committing the lock file or running composer update, its best to remove the telescope:publish command from your `post-update-cmd` scripts.

**Comment by ragingdave** [comment]
I do actually have a lock file committed, and that seems to have no bearing on this error happening. So to add a step to reproduce, ensure that the composer lock file is present, then re-run a `composer install --no-dev` and see that it fails with that same issue.

**Comment by paras-malhotra** [comment]
That's strange - here's an excerpt from the [Composer docs](https://getcomposer.org/doc/articles/scripts.md#command-events):

> post-update-cmd: occurs after the update command has been executed, or after the install command has been executed without a lock file present.

**Comment by ragingdave** [comment]
The issue isn't with the timing of when that post-update-cmd runs, it's the issue that's it's run after the install takes place, but if you don't have telescope installed (in a no-dev composer install) even with a lock file, laravel doesn't know about the command namespace and will error out. This means you can't actually add the publish command as a post-update-cmd if you don't have telescope installed everywhere, meaning more manual steps.

The previous non-prefixed command of just using the built in vendor:publish command did work with and without telescope installed, so this would basically be a breakage.

**Comment by paras-malhotra** [comment]
The issue isn't the timing, it's that `post-update-cmd` and `telescope:publish` shouldn't be executed (ever) in production if you have telescope as a dev dependency. The issue is why is `post-update-cmd` executing at all? As per the Composer docs it shouldn't be executed in production and if it doesn't execute, there would be no issues with this setup.

**Comment by paras-malhotra** [comment]
@ragingdave did you add the `"@php artisan telescope:publish --ansi"` in `post-update-cmd` or `post-install-cmd`? The subject of the issue says `post-install-cmd` but the description reads `post-update-cmd`

**Comment by ragingdave** [comment]
I actually have it in both, but that wouldn't the cause as regardless, the command isn't registered at all in laravel, so when it gets run to ensure that the server it's on is actually up to date, it will error out.

**Comment by paras-malhotra** [comment]
> I actually have it in both
That's the real issue. Remove it from `post-install-cmd` and it will work perfectly

> when it gets run
The idea is for it to never run in production, so there's no question of an error. You could have `"@php gibberish"` in your `post-update-cmd` and it still won't error out in production because the script will never run

**Comment by ragingdave** [comment]
you know, that's a very good point, and yep that solves it. Thanks!
