### ISSUE TITLE
[Error] Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Tjoosten** [laravel/telescope#98]
The monitored-tags api endpoint. Returns a 404 when the monitor is running after I press the scan button.

**Comment by andreshg112** [comment]
In Firefox it looks like: `Loading failed for the <script> with source “http://localhost/vendor/telescope/app.js?id=0daab09c64e9f87c81ab”.`

I think that the problem happens because I'm using Xampp insteand of Vagrant, Valet, Docker, `php artisan serve` or something like that, so `http://localhost` is not the base URL.

**Comment by andreshg112** [comment]
I'm using docker now and I got the same thing again. But this time, It shows a Vue error. I'll show it here later.

**Comment by andreshg112** [comment]
Oh, sorry!
My problem happens because I have installed https://github.com/renatomarinho/laravel-page-speed, so It transforms scripts. I had to disable it or add the exception `'/telescope/*'` in `config/laravel-page-speed.php` in order to make Telescope work.
